### PR TITLE
add: SUSE variables

### PR DESCRIPTION
**Pull request by castorsky**
I have added ca_path and ca_location for SUSE-based distros.
Tested on openSUSE Leap 15.5.

### CODE REVIEW

**Comment by infra-monkey** [comment]
Hello @castorsky 
Thank you for the PR.
Can you add the compatible platforms in [meta](https://github.com/infra-monkey/ansible_role_root_ca/blob/2e1e0824f564c2e06b0e456964122cb87efe521c/meta/main.yml#L10)?
Should be
```yaml
    - name: opensuse
      versions:
          - "15.5"
```
If you know it works on other version, feel free to add them

**Comment by castorsky** [comment]
Hello @infra-monkey 
I have made some molecule testing and added info about checked version to meta.
Can not add those tests to your repo because they need manual patching of debock's playbook in temporary directory.

**Comment by infra-monkey** [comment]
@castorsky 
Thank you. I will merge and release.
I'll add the molecule tests. I personally use only debian but it will not be too hard to test on other distros.

**Comment by infra-monkey** [comment]
@castorsky apparently ansible galaxy doesn't support the 15SP4 15SP5 releases for SLES. Only 15 according to https://galaxy.ansible.com/api/v1/platforms/?name=SLES
Can you adapt?

**Comment by castorsky** [comment]
> Can you adapt?

No problem :)
And if you will face some issues with testing SUSE you can peek at [my tests here](https://github.com/castorsky/ansible_role_root_ca/tree/test_suse_vars/molecule/suse).

**Comment by infra-monkey** [comment]
@castorsky merged and release (0.0.6)
Thank you for the PR

**Pull request merged**
